### ISSUE TITLE
[Error] Cordova: Cannot read property 'CastContext'

### ISSUE THREAD

**Issue by guilhermelirio** [Fenny/ChromecastJS#3]
Cordova uses HTML + JS + CSS. Is it possible to make it work, or only via the same browser?

Error:

```
chromecastjs.js:43 Uncaught TypeError: Cannot read property 'CastContext' of undefined
    at ChromecastJS.ChromecastJS.cast (file:///android_asset/www/js/chromecastjs.js:43:23)
    at cast (file:///android_asset/www/js/app.js:90:6)
    at HTMLButtonElement.onclick (file:///android_asset/www/index.html:99:102)
    at sendClick (file:///android_asset/www/js/framework7.js:4151:23)
    at Framework7.handleTouchEnd (file:///android_asset/www/js/framework7.js:4342:7)
    at file:///android_asset/www/js/framework7.js:3059:24
    at Array.forEach (native)
    at file:///android_asset/www/js/framework7.js:3058:18
    at Array.forEach (native)
    at Framework7.emit (file:///android_asset/www/js/framework7.js:3052:17)
```

**Comment by Fenny** [comment]
Hi @guilhermelirio 

Did you include the cast sender library?

```
<script src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></script>
```

**Comment by disiami** [comment]
Solo funciona con https
